<?php

/* Set 'enable' to '1' to verify you have configured
 * this file, and are ready to enable gpg key creation
 * for interBBS mail features.
 *
 * This does NOT enable/disable NoCeM. NoCeM is  
 * enabled in rslight.inc.php, but it DOES depend
 * on $rslight_gpg['gnupghome'] below.
*/
$rslight_gpg['enable'] = '0';

/* YOU MUST CONFIGURE 'domain_name' to your site
 * domain name
*/
$rslight_gpg['domain_name'] = "www.example.com";

// What nntp group to use to share mail data
$rslight_gpg['nntp_group'] = "rocksolid.shared.encryption";

// A real contact email address
$rslight_gpg['contact'] = "admin@example.com";

/* Below settings need not be changed if you are
 * ok with defaults
*/
// Where your .gpg data is kept
$rslight_gpg['gnupghome'] = $config_dir."/.gnupg";

// Don't change this
$rslight_gpg['from_email'] = "rslight@".$rslight_gpg['domain_name'];
