<?php

/* Set 'enable' to '1' to verify you have configured
 * this file, and are ready to enable gpg key creation
*/
$rslight_gpg['enable'] = '0';

/* YOU MUST CONFIGURE 'domain_name' to your site
 * domain name
*/
$rslight_gpg['domain_name'] = "www.example.com";

// What nntp group to use to share mail data
$rslight_gpg['nntp_group'] = "rocksolid.shared.encryption";

// What email address for sending notices
$rslight_gpg['from_email'] = "rslight@example.com";

// A real contact email address
$rslight_gpg['contact'] = "admin@example.com";

/* Below settings need not be changed if you are
 * ok with defaults
*/
// Where your .gpg data is kept
$rslight_gpg['gnupghome'] = $config_dir."/.gnupg";

