# These are the links at the top right of the site
# display name:url
mail:/rocksolid/index.php?page=mail
files:/rocksolid/index.php?page=files
groups:/common/grouplist.php
faq:/rocksolid/index.php?page=faq
register:/rocksolid/index.php?page=register
