# You must add the public key for
# each issuer listed to the directory
# set in gpg.conf
# Set GNUPGHOME to this directory
# when adding the key using gpg

i2pn2-nocem@i2pn2.org:spam
nocem@eternal-september.org:spam,misplaced_binary
