# You must add the public key for
# each issuer listed to the directory
# set in gpg.conf
#
# For multiple types for one issuer
# list types comma separated on one line
# ex: nocem-issuer@example.com:spam,flood,etc
#
# Set GNUPGHOME to this directory
# when adding the key using gpg

i2pn2-nocem@i2pn2.org:spam
nocem@eternal-september.org:spam,misplaced_binary
