<?php
/*
 * Production Mode Configuration
 * Generated by logging_control.sh
 */

// Return array of overrides
return array(
    // Enable production logging mode
    'disable_debug_logging' => true,
    'production_mode' => true,

    // Reduce spool verbosity
    'spoolnews_verbose' => false,
    'debug_articles' => false,

    // Cache optimization for production
    'cache_thread' => 3600,  // 1 hour cache
);
?>
