#!/bin/bash
# Production Logging Control Script for Rocksolid Light
# Usage: ./logging_control.sh [enable|disable|status]

# Auto-detect environment and set paths
if [[ -f "/etc/rslight/rslight.inc.php" ]]; then
    # Production environment
    CONFIG_DIR="/etc/rslight"
    WEB_DIR="/var/www/html/rocksolid"
elif [[ -f "$(dirname "$0")/../rslight.inc.php" ]]; then
    # Development environment - script in rslight/scripts/
    CONFIG_DIR="$(dirname "$0")/.."
    WEB_DIR="$(dirname "$0")/../../rocksolid"
else
    # Development fallback - try relative paths
    CONFIG_DIR="$(dirname "$0")/../.."
    WEB_DIR="$(dirname "$0")/../../rocksolid"
fi

# Override file is now in rslight/inc/
OVERRIDE_FILE="$CONFIG_DIR/inc/overrides.inc.php"
TEMPLATE_FILE="$CONFIG_DIR/overrides.inc.php.production"

show_usage() {
    echo "Usage: $0 [enable|disable|status]"
    echo ""
    echo "Commands:"
    echo "  enable  - Enable production logging mode (reduce DEBUG spam)"
    echo "  disable - Disable production logging mode (enable all debugging)"
    echo "  status  - Show current logging configuration"
    echo ""
    echo "Production mode significantly reduces log file sizes by disabling"
    echo "verbose DEBUG messages while keeping ERROR and important messages."
}

show_status() {
    echo "=== Rocksolid Light Logging Status ==="

    if [[ ! -f "$OVERRIDE_FILE" ]]; then
        echo "❌ No override file found - using default (verbose) logging"
        echo "📁 Override file: $OVERRIDE_FILE"
        return
    fi

    # Check for production mode settings
    local prod_mode=0
    local debug_disabled=0

    if grep -q "production_mode.*true" "$OVERRIDE_FILE" 2>/dev/null; then
        prod_mode=1
    fi

    if grep -q "disable_debug_logging.*true" "$OVERRIDE_FILE" 2>/dev/null; then
        debug_disabled=1
    fi

    if [[ $prod_mode -gt 0 || $debug_disabled -gt 0 ]]; then
        echo "✅ Production logging mode: ENABLED"
        echo "📉 DEBUG log spam: REDUCED"
        echo "🔍 ERROR logging: ENABLED"
    else
        echo "⚠️  Production logging mode: DISABLED"
        echo "📈 DEBUG log spam: ACTIVE (may fill logs quickly)"
        echo "🔍 All logging: ENABLED"
    fi

    echo "📁 Override file: $OVERRIDE_FILE"
    echo ""

    # Show log file sizes if they exist - try multiple possible locations
    local log_dirs=(
        "/var/spool/rslight/log"
        "$CONFIG_DIR/../spool/log"
        "$(dirname "$CONFIG_DIR")/spool/log"
    )

    for log_dir in "${log_dirs[@]}"; do
        if [[ -d "$log_dir" ]]; then
            echo "📊 Current log file sizes:"
            if ls "$log_dir"/*.log >/dev/null 2>&1; then
                du -sh "$log_dir"/*.log 2>/dev/null | head -5
            else
                echo "   No log files found in $log_dir"
            fi
            break
        fi
    done
}

enable_production() {
    echo "🔧 Enabling production logging mode..."

    # Create backup if override file exists
    if [[ -f "$OVERRIDE_FILE" ]]; then
        cp "$OVERRIDE_FILE" "$OVERRIDE_FILE.backup.$(date +%Y%m%d_%H%M%S)"
        echo "💾 Backed up existing override file"
    fi

    # Create production override file
    cat > "$OVERRIDE_FILE" << 'EOF'
<?php
/*
 * Production Mode Configuration
 * Generated by logging_control.sh
 */

// Return array of overrides
return array(
    // Enable production logging mode
    'disable_debug_logging' => true,
    'production_mode' => true,

    // Reduce spool verbosity
    'spoolnews_verbose' => false,
    'debug_articles' => false,

    // Cache optimization for production
    'cache_thread' => 3600,  // 1 hour cache
);
?>
EOF

    echo "✅ Production logging mode enabled"
    echo "📉 DEBUG log spam will be significantly reduced"
    echo "🔄 Restart web server and spooling processes for full effect"
}

disable_production() {
    echo "🔧 Disabling production logging mode..."

    if [[ -f "$OVERRIDE_FILE" ]]; then
        # Create backup
        cp "$OVERRIDE_FILE" "$OVERRIDE_FILE.backup.$(date +%Y%m%d_%H%M%S)"
        echo "💾 Backed up existing override file"

        # Remove or comment out production settings
        cat > "$OVERRIDE_FILE" << 'EOF'
<?php
/*
 * Development Mode Configuration
 * Generated by logging_control.sh
 */

// Return array of overrides
return array(
    // Disable production logging mode - enable all debugging
    'disable_debug_logging' => false,
    'production_mode' => false,

    // Enable verbose logging for debugging
    'spoolnews_verbose' => true,
    'debug_articles' => true,
);
?>
EOF
    else
        echo "ℹ️  No override file exists - verbose logging already active"
    fi

    echo "✅ Production logging mode disabled"
    echo "📈 Full DEBUG logging enabled (logs may grow quickly)"
    echo "🔄 Restart web server and spooling processes for full effect"
}

# Main script logic
case "${1:-}" in
    enable)
        enable_production
        echo ""
        show_status
        ;;
    disable)
        disable_production
        echo ""
        show_status
        ;;
    status)
        show_status
        ;;
    *)
        show_usage
        exit 1
        ;;
esac
